version: '3.8'
services:
  app:
    build: .
    container_name: fastapi-book-proj-app-1 
    ports:
      - "8000:8000"

  nginx:
    image: nginx:alpine
    container_name: fastapi-book-proj-nginx-1
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
